---
# http://module-build.sourceforge.net/META-spec.html
name:         Tao-DBI
version:      0.00_06
version_from: lib/Tao/DBI.pm
author:
  - Adriano Ferreira <ferreira@cpan.org>
license: perl
requires:
    DBI:                           1
recommends:
    Test::Pod:                     1.18
installdirs:  site

distribution_type: module
generated_by: ExtUtils::MakeMaker version 6.17
